### ISSUE TITLE
HiDPI causes improper display

### ISSUE THREAD

**Issue by vasi** [digidigital/OCRthyPDF-Essentials#11]
I have a monitor set to use 2x scaling in my Displays settings. When I try to use OCRthyPDF, the GUI ends up all wrong:

![ocrthypdf-scaled](https://user-images.githubusercontent.com/3305/164619182-36b5056e-0a1d-4112-aa01-81f7255bbcbb.png)

Notice how I don't even have access to fields like "Output type", it's stuck below the bottom of the window!

Everything is fine when I use a screen without scaling. Other scale factors (like 125%) produce the same problem.

I'm happy to do any testing that would be helpful, if you don't happen to have a monitor which is reasonable to run with a scaling factor. Thanks so much for this great tool!

Version: v0.6.3-30-g36735db (edge channel, same problem with stable)
OS: Ubuntu 22.04

**Comment by digidigital** [comment]
Hi Vasi,

I have changed the TabGroup to be computed instead of having a fixed size.
New version is currently building - please check the edge channel to see if this fixes your issue.
I am planning to update the snap to use core 20 and add a new splitter so you can expect another edge/beta release this weekend.

**Comment by vasi** [comment]
Wow, fixed! Thanks for the quick action.
