### ISSUE TITLE
snap v0.7.0-20-g92dca5c rev 137 does not recognize pngquant

### ISSUE THREAD

**Issue by thatso** [digidigital/OCRthyPDF-Essentials#18]
pngquant is installed with a version above the minimal required one:
```
> pngquant --version
2.17.0 (September 2021)
```
However, snap v0.7.0-20-g92dca5c rev 137 says its missing.
A revert back to rev 136 immediately fixed this.

**Comment by digidigital** [comment]
Thank you for reporting the bug.

The issue was that the dependencies of OCRmyPDF > 14.4.0 are not available in snap core20.

- OCRmyPDF will now be limited to version 14.4.0 until the snap is updated to use core22
- I have added jbig2enc in the snap

It would be great if you could test build 151 (available in snap channel latest/candidate) and report back if everything is still working as expected :)

**Comment by thatso** [comment]
Apologies for the late response - I'm on v0.7.0-58-gbd96751 build 152 meanwhile and no longer experience the reported issue. Thanks for your great work!
